---

- name: Start RabbitMQ server
  service:
    name: rabbitmq-server
    state: restarted

- name: Restart RabbitMQ server
  service:
    name: rabbitmq-server
    state: restarted

- name: Enable rabbitmq-server
  service:
    name: rabbitmq-server
    enabled: True
